package com.emlakjet.rabbitmqproducer.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;


// in h2 db we have to define user table name users because db useses user table already.
@Table(name = "users")
// we define this is my entity class
@Entity
// lombok anotayions
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class User {
    // we have to id parameter and our id generated by spring automaticly.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private String email;

}