package com.emlakjet.rabbitmqconsumer.model;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


// we define this is our entity class for spring
@Entity
// lombok anotayions
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder

public class SaleAdvertisement {
    // we have to id parameter and our id generated by spring automaticly
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String title;
    private String photo;
    private String detailMessage;
    private String priceGraphPath;


}